### ISSUE TITLE
[Epic] Modernize to latest Minecraft (1.13+ flattening, protocol compat, toolchain)

### ISSUE THREAD

**Issue by sakebomb** [sakebomb/RaspberryJuice#13]
## Goal
Update RaspberryJuice to run on a modern Minecraft/Bukkit server (current Spigot/Paper). This is a **rewrite of the block layer**, not a version bump, because the plugin is built entirely on the pre-1.13 numeric block-ID API.

## Why it's a rewrite, not a patch
Minecraft 1.13 (the "flattening") **removed numeric block IDs and data values**. The plugin depends on them pervasively:
- `World.getBlockTypeIdAt`, `Block.getTypeId`, `Block.setTypeIdAndData`, `Block.getData` — all removed
- `EntityType.getTypeId()` / `EntityType.fromId()` — deprecated/removed
- Numeric IDs are also part of the **wire protocol** sent to Python `mcpi` clients (`world.getBlock` returns an int id; `setBlock` takes an int id + byte data). So a naive port breaks every existing client script.

## Key decision: protocol compatibility
Pick one before implementation:
1. **Compatibility mapping layer** — maintain a legacy-numeric-ID ⇄ modern `Material`/`BlockData` table so existing `mcpi` scripts keep working. Preserves the ecosystem; the mapping is lossy/large and needs maintenance.
2. **New string-based protocol** — expose `Material` names / `BlockData` strings; requires updated Python client(s) and breaks old scripts.
3. **Hybrid** — support both, versioned by a handshake.

Recommendation: start with (1) for continuity, expose (2) as an opt-in.

## Workstream checklist
- [ ] Bump toolchain: modern `maven-compiler-plugin`, Java 17+ (Paper 1.20+ requires 17/21), target Spigot/Paper API `1.20.x`+.
- [ ] Decide + document the protocol-compatibility strategy (above).
- [ ] Replace all numeric block-ID calls with `Material`/`BlockData`.
- [ ] Replace `EntityType` id usage with modern `EntityType` handling.
- [ ] Rework `world.getEntityTypes` / `spawnEntity` for the modern entity registry.
- [ ] Refactor `handleCommand` into a dispatch map first (see the maintainability issue) — prerequisite that makes this tractable and testable.
- [ ] Add integration tests against a modern mock/server harness (MockBukkit).
- [ ] Update bundled Python `mcpi` client(s) and README accordingly.
- [ ] Verify on Paper (recommended) and Spigot.

## Dependencies
Depends on the command-dispatch refactor and benefits from the error-handling/concurrency fixes landing first.

## Severity / type
Epic — largest single effort; core objective of this fork.
---

## Related audit issues (from initial code audit)
Recommended landing order — hardening/refactor first, then the block-layer rewrite:

**Do first (unblock + de-risk):**
- [ ] #6 — Command-dispatch refactor (prerequisite for this epic)
- [ ] #7 — Error handling / logging
- [ ] #3 — Async chat data race
- [ ] #5 — Volatile flags & thread-safe queues
- [ ] #4 — Malformed-input crash

**Security / DoS (address before any non-localhost deploy):**
- [ ] #1 — Unauthenticated 0.0.0.0 bind
- [ ] #2 — Unbounded cuboid ops

**Correctness / polish:**
- [ ] #8 — getAbsPos wire format
- [ ] #10 — Negative-coord flooring
- [ ] #11 — Empty-server NPEs
- [ ] #9 — Busy-wait output thread
- [ ] #12 — Cleanup bundle

**Comment by sakebomb** [comment]
## Prototype results — build validated, surface nailed down

Branch [`feat/paper-modernization`](https://github.com/sakebomb/RaspberryJuice/tree/feat/paper-modernization) (commit `9f0d259`). Full write-up in [`docs/modernization-notes.md`](https://github.com/sakebomb/RaspberryJuice/blob/feat/paper-modernization/docs/modernization-notes.md).

**Toolchain validated:** POM migrated to Paper API `1.21.4-R0.1-SNAPSHOT` on Java 21 with `maven-compiler-plugin` 3.13.0, plus a committed **Maven Wrapper** (`./mvnw`, no system Maven). Dependencies resolve against `repo.papermc.io`; `./mvnw clean compile` reproduces the surface below.

**Removed-API surface is small and concentrated — 9 hard errors + 13 deprecations**, all the pre-1.13 flattening removals in five functions (`getBlock`/`getBlockWithData`, `getBlocks`, `updateBlock`, `setSign`) plus two `Material` sword renames.

**Linchpin finding — the mapping table is already in Bukkit.** The mcpi wire protocol speaks numeric block IDs; modern Minecraft has none. But Paper 1.21.4 *still ships the legacy bridge* (verified via `javap` on `paper-api`):
- `Bukkit.getUnsafe().fromLegacy(Material, byte)` → `BlockData` (write path)
- `toLegacy(Material)` + `Material.getId()` + 464 retained `LEGACY_*` materials (read path)

So the compatibility approach (option 1) does **not** require hand-authoring a mapping table — it's a thin `LegacyBlocks` adapter over the API's own bridge. This materially de-risks this epic and keeps every existing Python `mcpi` script working with zero client changes.

**Recommended landing order:** #6 (dispatch refactor) → `LegacyBlocks` adapter + round-trip tests → swap the 9+13 sites → MockBukkit integration test → live Paper smoke test with an mcpi client.

**Comment by sakebomb** [comment]
## Update — modern build + executing test suite (branch `feat/paper-modernization`)

Three commits in: build green **and** tests actually run now.

- `9f0d259` build scaffold (Paper API + Java 21 + Maven wrapper)
- `bc03e7f` block layer ported to `Material`/`BlockData` via `LegacyBlocks` — `./mvnw clean compile` green
- `fcfee35` test stack rebuilt: dropped dead cucumber-testng + jmockit 1.23, now **JUnit 5.14.4 + Mockito 5.23.0 + MockBukkit 4.108.0**; `./mvnw test` = **13 passing, 1 documented skip**

Bumped `paper.version` to **1.21.11** (latest 1.21.x; also what MockBukkit targets).

**Findings worth noting:**
- The old cucumber suite never executed under Maven — and its step-defs had an ABSOLUTE-origin bug that went unnoticed as a result. Ported scenarios now model `tick()`'s real origin logic.
- MockBukkit 4.108 does not implement `UnsafeValues.fromLegacy`, so the numeric-id→BlockData bridge can't be unit-tested in-process; it's `@Disabled` pending a **live Paper smoke test**.

**Next:** either the #6 dispatch refactor (on the now-tested baseline), or a live Paper 1.21.11 smoke test with a real mcpi client to prove end-to-end + unblock the disabled bridge test.

**Comment by sakebomb** [comment]
## ✅ Verified working on live Paper 1.21.11

Built the jar, ran it on a real Paper **1.21.11** server, and drove it with a raw Python 3 mcpi client. All round-trips pass through the modernized legacy bridge:

```
world.setBlock(0,10,0,41)      -> world.getBlock          = 41      (gold)
world.setBlock(0,11,0,35,14)   -> world.getBlockWithData  = 35,14   (red wool + data)
world.setBlock(0,10,0,0)       -> world.getBlock          = 0       (air)
```

The plugin loads cleanly (Paper remaps it to Mojang mappings) and the socket listener comes up on 4711. **This is the end-to-end proof that RaspberryJuice runs on the latest Minecraft.**

**Two findings from the live run** (commit `949dc1b`):
1. The write path silently no-op'd at first: under Paper's plugin remapper a modern (`api-version`) plugin sees only *modern* materials from `Material.values()`, so the `isLegacy()` filter found nothing and the id→Material map built empty. Fixed by building the map via `UnsafeValues.toLegacy` over modern materials (same conversion the read path uses), lazily.
2. `plugin.yml` needed `api-version: '1.21'` for a clean modern load.

Reproducible check committed at `scripts/smoke_test.py`. The `LegacyBlocksTest` bridge case stays `@Disabled` (MockBukkit can't do `fromLegacy`); the live smoke test covers it instead.

Branch now at 4 commits; build + 13 unit tests green, live smoke test green.

**Comment by sakebomb** [comment]
## Modernization + hardening complete — PR #15

Branch `feat/paper-modernization` (10 commits) is up as **#15**. Summary of what shipped:

- ✅ Builds & runs on **Paper 1.21.11 / Java 21**, verified live end-to-end
- ✅ Block + entity numeric-id layers modernized (legacy bridge, isolated); zero deprecation warnings outside the `Legacy*` adapters
- ✅ Security/DoS/concurrency/robustness fixes: closes #1, #2, #3, #4, #5, #7, #8, #9, #10, #11
- ✅ Test harness rebuilt (JUnit 5 / Mockito / MockBukkit): 23 tests, live smoke script
- ✅ README updated for the fork

**Remaining (follow-ups):**
- #6 — dispatch-map refactor of `handleCommand` (deliberately deferred: large internal refactor, best done with broader per-command tests first rather than rushed)
- #12 — minor cleanup leftovers (committed jars, magic-number constants, welcome-broadcast config flag)
- #14 — Adventure/chat API migration (the only remaining deprecations)

The core goal — **RaspberryJuice working on the latest Minecraft** — is done and proven.

**Comment by sakebomb** [comment]
## Follow-up progress
- **#16 merged** — `handleCommand` split into three focused dispatch handlers (partially addresses #6; the unreadable 470-line method is gone).

Remaining open: #6 (optional full map refinement), #12 (minor cleanup), #14 (Adventure/chat migration). Core goal (runs on latest Minecraft) shipped in #15.

**Comment by sakebomb** [comment]
## Follow-up progress
- **#17 merged** — Adventure/chat migration (closes #14). All numeric-id **and** chat/name deprecations are now gone from the codebase (only unrelated `Sign.setLine`/`AbstractArrow.getAttachedBlock` remain as separate follow-ups). An independent review caught an inaccurate "identical strings" claim (plain-text strips `§` colour codes); addressed by documenting the intentional normalization, keeping `§` interpretation for `chat.post`, and adding tests.

`master` is green (29 tests). Remaining open: #6 (optional full dispatch-map), #12 (minor cleanup).
